version: '3'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rate-limiter
    depends_on:
      - redis
    ports:
      - "8080:8080"